# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-sample2
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  orchestration:
    pre:
      name: "pre"
      image: "ubuntu"
      entrypoint: "bash"
      args: ["./pre.sh", "$PROJECT_ID", "$BUILD_ID"]
    post:
      name: "post"
      image: "gcr.io/cloud-builders/gsutil"
      entrypoint: "bash"
      args: ["./post.sh"] 
  info:
    title: Sample app
    source:
      repo: https://github.com/bharathkkb/sample2.git
      sourceType: git
    version: 0.1.5
    actuationTool:
      flavor: Terraform
      version: '>= 0.13'
    description:
      tagline: Sample
      detailed: |-
        Sample detailed
      architecture:
      - arch 1
      - arch 2
  interfaces:
    variables:
    - name: project_id
      description: Project ID to deploy bucket
      varType: string
      required: true
    - name: content
      description: Content to put in the bucket
      varType: string
      required: true
    outputs:
    - name: gcs
      description: Created bucket
    - name: object
      description: Created object
  requirements:
    roles:
    - level: Project
      roles:
      - roles/owner
    services:
    - storage.googleapis.com
